### PR TITLE
CashAccount support

### PR DESCRIPTION
**Pull request by paOol**
https://github.com/Bitcoin-com/badger/issues/25

### CODE REVIEW

**Comment by paOol** [comment]
merged 
https://github.com/Bitcoin-com/badger/pull/76
into this PR.

**Comment by monsterbitar** [comment]
Let me know if there is anything I can do to speed up this process.

**Comment by emergent-reasons** [comment]
In case it helps, there is a good amount of [test data](https://gitlab.com/cash-accounts/specification/blob/master/TEST.md) for validating implementations.

**Comment by paOol** [comment]
combined with https://github.com/Bitcoin-com/badger/pull/143 to also include imports, and registrations,

**Pull request closed without merging**
